#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


TOTAL_STAGES=8

# ──────────────────────────────────────────────────────────────────────────
# Interactivity guard. Added after a run on 2026-08-17 in which stdin was not
# a terminal: every read() returned EOF instantly, all ten values were written
# empty, and the stage-5 confirm fell through to its default. That produced
# REVOCATION_SUPPORTED=no — a phantom answer to the single most consequential
# question in the fixture, indistinguishable in .env from a real one.
#
# A wizard whose output feeds a proof must not be able to invent an answer.
# ──────────────────────────────────────────────────────────────────────────

die() { printf '\n  %s✗ %s%s\n\n' "$RED" "$1" "$RESET" >&2; exit 1; }

# If stdin is not a terminal but a terminal is reachable, attach to it. This
# covers editor terminals and wrappers that redirect stdin while a real human
# is still watching. Only refuse when no terminal exists at all.
if [[ ! -t 0 && -r /dev/tty ]]; then
  exec < /dev/tty || true
fi

if [[ ! -t 0 ]]; then
  die "stdin is not a terminal, and /dev/tty is not reachable — refusing to run.
  Every prompt would read EOF and record an empty value silently.
  Open a terminal and run:  bash scripts/setup-proof-fixture.sh
  Do not run it through an AI harness, a pipe, or a run button."
fi

# need KEY "Prompt" — like ask, but will not accept an empty value.
need() {
  local key="$1" prompt="$2"
  while :; do
    ask "$key" "$prompt"
    [[ -n "${!key}" ]] && return 0
    warn "required — this value ends up in .env and the proof reads it."
  done
}

# need_token KEY "Prompt" — read the Notion token, then prove it works before
# accepting it.
#
# Hidden input is not used. On Git Bash for Windows a Ctrl-V into a `read -rs`
# prompt inserts a literal \x16 and the terminal's bracketed-paste escapes land
# inside the value. Observed 2026-08-17: a 161-character value holding \x16,
# \x1b, '[', ';' and '~', with the real token corrupted inside it. It failed
# with an empty-bodied HTTP 400 that looked like a server fault.
#
# So: visible input (you can see what arrived), control characters stripped,
# shape checked, and a live read-only GET /v1/users/me before the value is
# allowed into .env. A token that cannot authenticate is not a token.
need_token() {
  local key="$1" prompt="$2" raw clean code
  while :; do
    ask "$key" "$prompt"
    raw="${!key}"
    clean=$(printf '%s' "$raw" | tr -d '[:cntrl:]' | grep -oE 'ntn_[A-Za-z0-9]+' | head -n1 || true)
    if [[ -z "$clean" ]]; then
      warn "that does not contain an ntn_ token — paste the Internal Integration Secret."
      continue
    fi
    if [[ "$clean" != "$raw" ]]; then
      note "stripped ${#raw} chars of paste artefacts down to ${#clean}."
    fi
    printf '  checking the token against Notion (read-only)... '
    code=$(curl -s -o /dev/null -w '%{http_code}' \
      https://api.notion.com/v1/users/me \
      -H "Authorization: Bearer $clean" \
      -H "Notion-Version: 2022-06-28" || echo 000)
    case "$code" in
      200) printf '%sOK%s\n' "$GREEN" "$RESET"; printf -v "$key" '%s' "$clean"; return 0 ;;
      401) printf '%srejected%s\n' "$RED" "$RESET"
           warn "Notion says the token is invalid. Re-copy it from the integration's"
           warn "Configuration tab. Use right-click paste, not Ctrl-V." ;;
      000) printf '%sno network%s\n' "$YELLOW" "$RESET"
           if must_answer "Cannot reach Notion. Accept the token unverified?"; then
             printf -v "$key" '%s' "$clean"; return 0
           fi ;;
      *)   printf '%sHTTP %s%s\n' "$RED" "$code" "$RESET"
           warn "unexpected response — try pasting again." ;;
    esac
  done
}

# must_answer "question" — y/n with NO default. Loops until the human types
# one or the other. Used where a default would be mistaken for evidence.
must_answer() {
  local reply=""
  while :; do
    printf '  %s? %s [y/n] ' "$YELLOW" "$1"
    read -r reply || die "stdin closed mid-question — no answer recorded."
    case "$reply" in
      [Yy]*) return 0 ;;
      [Nn]*) return 1 ;;
      *) warn "type y or n — this answer is recorded as a proof result." ;;
    esac
  done
}

banner "workspace_lint — 72-hour proof fixture"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Notion integration — read-only token"
say "The proof needs an internal integration. Read-only is a product boundary,"
say "not a preference: Principle 7 says the process requests no write capability."
open_url "https://www.notion.so/profile/integrations"
step "Click 'New integration'."
step "Name it: workspace-lint-proof"
step "Associated workspace: pick the workspace that will hold the fixture."
step "Type: Internal."
warn "Capabilities — set these EXACTLY:"
note "    Content Capabilities : Read content        ONLY"
note "    Comment Capabilities : none"
note "    User Capabilities    : Read user information without email addresses"
note "  Insert content and Update content must both be OFF."
say ""
say "Then open the integration's Configuration tab and reveal the Internal"
say "Integration Secret."
need_token NOTION_TOKEN "Paste the integration secret (starts ntn_ — use right-click paste):"
write_env NOTION_TOKEN "$NOTION_TOKEN"
write_env NOTION_VERSION "2026-03-11"
note "NOTION_VERSION is pinned by ADR-0002 decision 4 — it must carry request_status."
note "No GitHub secret is set: there is no CI yet and the proof runs locally only."
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Fixture root — create and connect"
say "One top-level page is the declared root for the whole proof."
open_url "https://www.notion.so"
step "Create a new top-level page named: wl-proof-fixture"
step "Open its ... menu -> Connections -> Connect to -> workspace-lint-proof"
say ""
say "The page ID is the 32-character hex string at the end of the URL,"
say "before any '?'. Example: notion.so/wl-proof-fixture-<32 hex chars>"
need FIXTURE_ROOT_ID "Paste the fixture root page ID:"
write_env FIXTURE_ROOT_ID "$FIXTURE_ROOT_ID"
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Pagination page — forces block-children paging"
say "Proof question 7: can enumeration be separated from fetching?"
say "That needs a page with more than 100 block children, because 100 is the"
say "default page size for GET /v1/blocks/{id}/children."
say ""
say "Generating 150 lines for you to paste..."
: > .proof-fixture-blocks.txt
for i in $(seq 1 150); do
  printf 'fixture block %03d - filler content for pagination testing\n' "$i" >> .proof-fixture-blocks.txt
done
say "Written to .proof-fixture-blocks.txt (150 lines)."
step "Open that file, select all, copy."
step "Create a child page of wl-proof-fixture named: wl-pagination"
step "Paste. Notion makes each line its own paragraph block."
need PAGINATION_PAGE_ID "Paste the wl-pagination page ID:"
write_env PAGINATION_PAGE_ID "$PAGINATION_PAGE_ID"
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Data source — paging order and a type-changeable property"
say "Two questions here. Q3: is result order stable across two identical"
say "paginated calls? Q2: does a property ID survive a property type change?"
say ""
say "Generating a 150-row CSV..."
printf 'Name,Status,Owner,Ref\n' > .proof-fixture-rows.csv
for i in $(seq 1 150); do
  printf 'row %03d,Active,unassigned,%d\n' "$i" "$i" >> .proof-fixture-rows.csv
done
say "Written to .proof-fixture-rows.csv (150 rows)."
step "Create a child page of wl-proof-fixture named: wl-dataset"
step "Inside it, type /database and choose Database - Full page."
step "Use ... -> Merge with CSV, and pick .proof-fixture-rows.csv"
warn "Do NOT change any property type yet — that is a proof step, not setup."
say ""
say "The data source ID is the 32-hex string in the URL of the database page."
need FIXTURE_DS_ID "Paste the wl-dataset data source ID:"
write_env FIXTURE_DS_ID "$FIXTURE_DS_ID"
write_env TYPE_CHANGE_PROP "Status"
note "The proof will change Status from Select to Text and re-read its property ID."
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Revocation probe — this stage IS a proof result"
say "Notion documents that a connection inherits to all children:"
note "  'When you connect a page and/or database to an integration,"
note "   all child entities come along for the ride.'"
say ""
say "Whether a single child can then be UN-shared is not established. The"
say "research marks it (C) — community reports, no reproduced primary source."
say "So do not assume it works. Attempt it, and record what you actually see."
say ""
step "Create a child page of wl-proof-fixture named: wl-revoke-parent"
step "Create a child page of THAT named: wl-revoke-child"
step "Open wl-revoke-child -> ... -> Connections."
say ""
warn "Look for an option to remove or disable workspace-lint-proof on this child."
need REVOKE_PARENT_ID "Paste the wl-revoke-parent page ID:"
need REVOKE_CHILD_ID "Paste the wl-revoke-child page ID:"
write_env REVOKE_PARENT_ID "$REVOKE_PARENT_ID"
write_env REVOKE_CHILD_ID "$REVOKE_CHILD_ID"
if must_answer "Did Notion let you remove the connection from the CHILD only?"; then
  write_env REVOCATION_SUPPORTED "yes"
  say ""
  say "Recorded: selective revocation exists. The proof can now test whether the"
  say "child_page block stays visible in the parent while the child 404s."
else
  write_env REVOCATION_SUPPORTED "no"
  say ""
  warn "Recorded: no selective revocation. This is a finding, not a setup failure."
  note "  It would mean every descendant of a declared root is always readable,"
  note "  so 'unreached' inside a declared root could only come from rate limits"
  note "  and pagination — never from permissions. That narrows ADR-0005's"
  note "  evidence-sufficiency axis and must be written up before the proof runs."
fi
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Undetectable hole — a page outside the grant"
say "The contrast case. A subtree whose root was never shared is invisible:"
say "no block in the readable graph references it. A LINK to it, from inside"
say "the grant, is the only trace — and it produces REF001 with an unreachable"
say "target, which is NOT the same thing as an unreached gap."
say ""
step "Create a SECOND top-level page named: wl-outside-grant"
warn "Do NOT connect the integration to it. That is the whole point."
step "Inside wl-proof-fixture, add a link to wl-outside-grant."
ask UNSHARED_PAGE_ID "Paste the wl-outside-grant page ID:"
write_env UNSHARED_PAGE_ID "$UNSHARED_PAGE_ID"
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Real workspace root — optional"
say "Proof question 8 asks how often 'disclaimed' fires on a REAL workspace."
say "A hand-built fixture cannot answer that; only real data can."
say ""
say "If you want that measured, connect the integration to one real top-level"
say "page and paste its ID. Leave blank to skip."
warn "Read-only, and nothing is written. Skip it if the content is sensitive."
ask REAL_ROOT_ID "Real workspace root page ID (Enter to skip):"
if [[ -n "${REAL_ROOT_ID:-}" ]]; then
  write_env REAL_ROOT_ID "$REAL_ROOT_ID"
else
  SKIPPED+=("proof Q8 — no real workspace root declared; disclaimed frequency stays unmeasured")
  note "Skipped. Question 8 stays open."
fi
pause

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Close out"
say "Writing .env.example so the shape is in git without the secret."
{
  echo "# workspace_lint — 72-hour proof fixture"
  echo "# Copy to .env and fill. .env is gitignored; never commit a real token."
  echo "NOTION_TOKEN="
  echo "NOTION_VERSION=2026-03-11"
  echo "FIXTURE_ROOT_ID="
  echo "PAGINATION_PAGE_ID="
  echo "FIXTURE_DS_ID="
  echo "TYPE_CHANGE_PROP=Status"
  echo "REVOKE_PARENT_ID="
  echo "REVOKE_CHILD_ID="
  echo "REVOCATION_SUPPORTED="
  echo "UNSHARED_PAGE_ID="
  echo "REAL_ROOT_ID="
} > .env.example
say "Wrote .env.example"
rm -f .proof-fixture-blocks.txt .proof-fixture-rows.csv
say "Removed scratch files"
say ""
warn "Two proof questions are OUT OF REACH of this fixture. Not dropped — named:"
note "  Q4 — the ~11,200-object search ceiling. Needs a workspace with more than"
note "       11,200 objects. Cannot be hand-built. Test on real data or defer."
note "  Q5 — is Semgrep's 'skipped' output verbose-gated. Nothing to do with"
note "       Notion; it is a local Semgrep CLI test."
SKIPPED+=("proof Q4 — 11,200-object search ceiling needs a large real workspace")
SKIPPED+=("proof Q5 — Semgrep verbose-gating is a local CLI test, not a Notion one")
pause

finish
